/**
 * Language → Devicon class mapping
 * Built from https://github.com/devicons/devicon/blob/master/devicon.json
 */

const LANG_ICONS = {
  // Programming Languages
  python: 'devicon-python-plain',
  javascript: 'devicon-javascript-plain',
  typescript: 'devicon-typescript-plain',
  java: 'devicon-java-plain',
  c: 'devicon-c-plain',
  cpp: 'devicon-cplusplus-plain',
  'c++': 'devicon-cplusplus-plain',
  csharp: 'devicon-csharp-plain',
  'c#': 'devicon-csharp-plain',
  go: 'devicon-go-original-wordmark',
  golang: 'devicon-go-original-wordmark',
  rust: 'devicon-rust-original',
  ruby: 'devicon-ruby-plain',
  php: 'devicon-php-plain',
  swift: 'devicon-swift-plain',
  kotlin: 'devicon-kotlin-plain',
  dart: 'devicon-dart-plain',
  scala: 'devicon-scala-plain',
  lua: 'devicon-lua-plain',
  perl: 'devicon-perl-plain',
  r: 'devicon-r-plain',
  julia: 'devicon-julia-plain',
  elixir: 'devicon-elixir-plain',
  erlang: 'devicon-erlang-plain',
  haskell: 'devicon-haskell-plain',
  clojure: 'devicon-clojure-line',
  clojurescript: 'devicon-clojurescript-plain',
  fsharp: 'devicon-fsharp-plain',
  'f#': 'devicon-fsharp-plain',
  ocaml: 'devicon-ocaml-plain',
  nim: 'devicon-nim-plain',
  zig: 'devicon-zig-original',
  crystal: 'devicon-crystal-original',
  fortran: 'devicon-fortran-original',
  cobol: 'devicon-cobol-original',
  groovy: 'devicon-groovy-plain',
  objectivec: 'devicon-objectivec-plain',
  'objective-c': 'devicon-objectivec-plain',
  prolog: 'devicon-prolog-plain',
  solidity: 'devicon-solidity-plain',
  matlab: 'devicon-matlab-plain',
  racket: 'devicon-racket-plain',
  ballerina: 'devicon-ballerina-original',
  purescript: 'devicon-purescript-original',
  delphi: 'devicon-delphi-plain',
  visualbasic: 'devicon-visualbasic-plain',
  vb: 'devicon-visualbasic-plain',
  processing: 'devicon-processing-plain',
  wasm: 'devicon-wasm-original',
  webassembly: 'devicon-wasm-original',
  apl: 'devicon-apl-plain',
  cairo: 'devicon-cairo-plain',
  ceylon: 'devicon-ceylon-plain',
  coffeescript: 'devicon-coffeescript-original',
  haxe: 'devicon-haxe-plain',
  vala: 'devicon-vala-plain',
  vyper: 'devicon-vyper-original',
  rexx: 'devicon-rexx-plain',

  // Shell / Scripting
  bash: 'devicon-bash-plain',
  sh: 'devicon-bash-plain',
  shell: 'devicon-bash-plain',
  zsh: 'devicon-zsh-plain',
  powershell: 'devicon-powershell-plain',
  awk: 'devicon-awk-plain-wordmark',

  // Web / Markup / Config
  html: 'devicon-html5-plain',
  html5: 'devicon-html5-plain',
  css: 'devicon-css3-plain',
  css3: 'devicon-css3-plain',
  sass: 'devicon-sass-original',
  scss: 'devicon-sass-original',
  less: 'devicon-less-plain-wordmark',
  stylus: 'devicon-stylus-original',
  json: 'devicon-json-plain',
  xml: 'devicon-xml-plain',
  yaml: 'devicon-yaml-plain',
  yml: 'devicon-yaml-plain',
  toml: 'devicon-yaml-plain',
  markdown: 'devicon-markdown-original',
  md: 'devicon-markdown-original',
  tex: 'devicon-tex-original',
  latex: 'devicon-latex-original',
  svg: 'devicon-xml-plain',
  graphql: 'devicon-graphql-plain',
  pug: 'devicon-pug-plain',
  handlebars: 'devicon-handlebars-original',
  htmx: 'devicon-htmx-plain',

  // Frontend Frameworks
  react: 'devicon-react-original',
  jsx: 'devicon-react-original',
  tsx: 'devicon-react-original',
  vue: 'devicon-vuejs-plain',
  vuejs: 'devicon-vuejs-plain',
  svelte: 'devicon-svelte-plain',
  angular: 'devicon-angular-plain',
  angularjs: 'devicon-angularjs-plain',
  nextjs: 'devicon-nextjs-original-wordmark',
  nuxt: 'devicon-nuxt-original',
  nuxtjs: 'devicon-nuxtjs-plain',
  gatsby: 'devicon-gatsby-original',
  ember: 'devicon-ember-original-wordmark',
  astro: 'devicon-astro-plain',
  solidjs: 'devicon-solidjs-plain',
  qwik: 'devicon-qwik-plain',
  jquery: 'devicon-jquery-plain',
  backbonejs: 'devicon-backbonejs-plain',
  d3js: 'devicon-d3js-plain',
  threejs: 'devicon-threejs-original',

  // Backend Frameworks
  django: 'devicon-django-plain',
  flask: 'devicon-flask-original',
  fastapi: 'devicon-fastapi-plain',
  rails: 'devicon-rails-plain',
  spring: 'devicon-spring-original',
  express: 'devicon-express-original',
  nestjs: 'devicon-nestjs-original',
  laravel: 'devicon-laravel-original',
  phoenix: 'devicon-phoenix-original',
  dotnet: 'devicon-dot-net-plain',
  '.net': 'devicon-dot-net-plain',
  dotnetcore: 'devicon-dotnetcore-plain',
  grails: 'devicon-grails-plain',
  fiber: 'devicon-fiber-plain',
  fastify: 'devicon-fastify-plain',
  symfony: 'devicon-symfony-original',

  // Databases
  sql: 'devicon-azuresqldatabase-plain',
  mysql: 'devicon-mysql-original',
  postgresql: 'devicon-postgresql-plain',
  postgres: 'devicon-postgresql-plain',
  sqlite: 'devicon-sqlite-plain',
  mongodb: 'devicon-mongodb-plain',
  redis: 'devicon-redis-plain',
  cassandra: 'devicon-cassandra-plain',
  neo4j: 'devicon-neo4j-plain',
  elasticsearch: 'devicon-elasticsearch-plain-wordmark',
  dynamodb: 'devicon-dynamodb-plain',
  couchdb: 'devicon-couchdb-plain',
  mariadb: 'devicon-mariadb-original',
  firebase: 'devicon-firebase-plain',
  supabase: 'devicon-supabase-plain',
  prisma: 'devicon-prisma-original',
  sequelize: 'devicon-sequelize-plain',
  mongoose: 'devicon-mongoose-original',
  cosmosdb: 'devicon-cosmosdb-plain',

  // DevOps / Infra
  docker: 'devicon-docker-plain',
  kubernetes: 'devicon-kubernetes-plain',
  terraform: 'devicon-terraform-plain',
  ansible: 'devicon-ansible-plain',
  nginx: 'devicon-nginx-original',
  jenkins: 'devicon-jenkins-line',
  github: 'devicon-github-original',
  githubactions: 'devicon-githubactions-plain',
  gitlab: 'devicon-gitlab-plain',
  git: 'devicon-git-plain',
  linux: 'devicon-linux-plain',
  ubuntu: 'devicon-ubuntu-plain',
  debian: 'devicon-debian-plain',
  centos: 'devicon-centos-plain',
  fedora: 'devicon-fedora-plain',
  archlinux: 'devicon-archlinux-plain',
  nixos: 'devicon-nixos-plain',
  prometheus: 'devicon-prometheus-original',
  grafana: 'devicon-grafana-plain',
  vagrant: 'devicon-vagrant-plain',
  consul: 'devicon-consul-original',
  packer: 'devicon-packer-plain',
  pulumi: 'devicon-pulumi-plain',
  helm: 'devicon-helm-original',
  argocd: 'devicon-argocd-plain',
  circleci: 'devicon-circleci-plain',
  travis: 'devicon-travis-plain',
  podman: 'devicon-podman-plain',

  // Build / Package
  npm: 'devicon-npm-original-wordmark',
  yarn: 'devicon-yarn-original',
  pnpm: 'devicon-pnpm-plain',
  webpack: 'devicon-webpack-plain',
  vite: 'devicon-vitejs-plain',
  rollup: 'devicon-rollup-plain',
  gradle: 'devicon-gradle-original',
  maven: 'devicon-maven-plain',
  cmake: 'devicon-cmake-plain',
  bun: 'devicon-bun-plain',
  bazel: 'devicon-bazel-plain',
  composer: 'devicon-composer-line',
  poetry: 'devicon-poetry-plain',

  // Editors / IDEs
  vim: 'devicon-vim-plain',
  neovim: 'devicon-neovim-plain',
  vscode: 'devicon-vscode-plain',
  intellij: 'devicon-intellij-plain',
  emacs: 'devicon-emacs-original',
  atom: 'devicon-atom-original',
  pycharm: 'devicon-pycharm-plain',
  webstorm: 'devicon-webstorm-plain',
  goland: 'devicon-goland-plain',
  rider: 'devicon-rider-plain',
  clion: 'devicon-clion-plain',

  // Data Science / ML
  jupyter: 'devicon-jupyter-plain',
  numpy: 'devicon-numpy-plain',
  pandas: 'devicon-pandas-plain',
  tensorflow: 'devicon-tensorflow-original',
  pytorch: 'devicon-pytorch-original',
  matplotlib: 'devicon-matplotlib-plain',
  keras: 'devicon-keras-plain',
  scikitlearn: 'devicon-scikitlearn-plain',
  opencv: 'devicon-opencv-plain',
  anaconda: 'devicon-anaconda-original',
  plotly: 'devicon-plotly-plain',
  streamlit: 'devicon-streamlit-plain',

  // Mobile
  android: 'devicon-android-plain',
  flutter: 'devicon-flutter-plain',
  reactnative: 'devicon-reactnative-original',
  ionic: 'devicon-ionic-original',
  xamarin: 'devicon-xamarin-original',

  // Game Engines
  unity: 'devicon-unity-plain',
  unrealengine: 'devicon-unrealengine-original',
  godot: 'devicon-godot-plain',
  love2d: 'devicon-love2d-plain',

  // Testing
  jest: 'devicon-jest-plain',
  mocha: 'devicon-mocha-plain',
  pytest: 'devicon-pytest-plain',
  rspec: 'devicon-rspec-plain',
  junit: 'devicon-junit-plain',
  cypressio: 'devicon-cypressio-plain',
  playwright: 'devicon-playwright-plain',
  selenium: 'devicon-selenium-original',
  vitest: 'devicon-vitest-plain',
  cucumber: 'devicon-cucumber-plain',
  storybook: 'devicon-storybook-plain',

  // Cloud
  amazonwebservices: 'devicon-amazonwebservices-plain-wordmark',
  aws: 'devicon-amazonwebservices-plain-wordmark',
  googlecloud: 'devicon-googlecloud-plain',
  gcp: 'devicon-googlecloud-plain',
  azure: 'devicon-azure-plain',
  digitalocean: 'devicon-digitalocean-original',
  heroku: 'devicon-heroku-original',
  vercel: 'devicon-vercel-original',
  netlify: 'devicon-netlify-plain',
  cloudflare: 'devicon-cloudflare-plain',
  railway: 'devicon-railway-original',

  // Misc
  arduino: 'devicon-arduino-plain',
  raspberrypi: 'devicon-raspberrypi-plain',
  electron: 'devicon-electron-original',
  tauri: 'devicon-tauri-plain',
  figma: 'devicon-figma-plain',
  blender: 'devicon-blender-original',
  wordpress: 'devicon-wordpress-plain',
  drupal: 'devicon-drupal-plain',
  tailwindcss: 'devicon-tailwindcss-original',
  bootstrap: 'devicon-bootstrap-plain',
  materialui: 'devicon-materialui-plain',
  socketio: 'devicon-socketio-original',
  grpc: 'devicon-grpc-plain',
  rabbitmq: 'devicon-rabbitmq-original',
  swagger: 'devicon-swagger-plain',
  postman: 'devicon-postman-plain',
  insomnia: 'devicon-insomnia-plain',
  eslint: 'devicon-eslint-plain',
  babel: 'devicon-babel-plain',
  trpc: 'devicon-trpc-plain',
  rxjs: 'devicon-rxjs-plain',
  redux: 'devicon-redux-original',
  mobx: 'devicon-mobx-plain',
  renpy: 'devicon-renpy-plain',
  sdl: 'devicon-sdl-plain',
  opengl: 'devicon-opengl-plain',
  vulkan: 'devicon-vulkan-original',
  plaintext: '',
  text: '',
  txt: '',
};

export function getLangIcon(lang) {
  const key = (lang || '').toLowerCase().trim();
  const cls = LANG_ICONS[key];
  if (cls) return `<i class="${cls} colored"></i>`;
  if (cls === '') return `<i class="devicon-devicon-plain colored"></i>`;
  return `<span class="lang-icon-text">${key.slice(0, 2).toUpperCase() || 'TX'}</span>`;
}
